---
kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node:16.13.1-alpine
    commands:
      - yarn install

  - name: test
    image: node:16.13.1-alpine
    commands:
      - yarn test
