name: Main

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: npm

      - name: Install dependencies
        run: npm clean-install

      - name: Lint
        run: npm run lint
